### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by mzprose** [YotamNitzan/ID-disentanglement#1]
Hello ,i don't know how to run test.py?can you tell me

python test.py 
    Name
    --pretrained_models_path PRETRAINED_MODELS_PATH \
    --load_checkpoint PATH_TO_WEIGHTS \
    --id_dir DIR_OF_IMAGES_FOR_ID \
    --attr_dir DIR_OF_IMAGES_FOR_ATTR \
    --output_dir DIR_FOR_OUTPUTS \
    --test_func infer_on_dirs

what the 'Name' to set?

**Comment by YotamNitzan** [comment]
Hi,
"Name" is a parameter that specifies the name of this experiment. A directory with this name will be created and all results will be stored in it.

**Comment by mzprose** [comment]
thank you very much!
