### ISSUE TITLE
Wrong data format for  error

### ISSUE THREAD

**Issue by molo32** [YotamNitzan/ID-disentanglement#5]
can you explain what you mean by name attr id

can illustrate the hierarchy there must be for this to work

I have it like this

! python test.py molo2 --pretrained_models_path "/ content / ID-disentanglement / pre" \
     --load_checkpoint "/ content / drive / MyDrive / checkpoint" \
     --input_dir "/ input /" \
     --output_dir "/ out" \
     --test_func interpolate

hierarchy

```
input folder
  id folder
      id.jpg
      id1.jpg

   attr folder
        att1.jpg


```

I get this error

Wrong data format for id
Wrong data format for attr

**Comment by YotamNitzan** [comment]
Hi,
The format should be such that in every directory there are exactly three images. Two for id and one for attr or two for attr and one for id. I suggest you look [here](https://github.com/YotamNitzan/ID-disentanglement/blob/2e66b43f00521d06c8705eb7c56ae4ee10b153f9/inference.py#L78-L86) for the place where the error is raised. The code is also pasted here below:

```
ids = list(d.glob('*id*'))
attrs = list(d.glob('*attr*'))


if len(ids) == 1 and len(attrs) == 2:
    const = 'id'
elif len(ids) == 2 and len(attrs) == 1:
    const = 'attr'
else:
    print(f'Wrong data format for {d.name}')
```
